stages:
  - create_image
  - tag_image
  - registry_image
before_script:
  - docker info

job 1:
  stage: create_image
  script:
    - docker build -t centos/ansible .

job 2:
  stage: tag_image
  script:
    - docker tag centos/ansible localhost:5000/ansible:v1

job 3:
  stage: registry_image
  script:
    - docker push localhost:5000/ansible:v1