stages:
  - create_image
  - test
  - tag_image
  - registry_image
except:
  changes:
    - README.md

before_script:
  - docker info

job create:
  stage: create_image
  script:
    - docker build -t centos/ansible .

job test:
  stage: test
  script:
    - docker run centos/ansible ansible --version

job tagged:
  stage: tag_image
  script:
    - docker tag centos/ansible localhost:5000/ansible

job registry:
  stage: registry_image
  script:
    - docker push localhost:5000/ansible


