stages:
  - create_image
  - test
  - tag_image
  - registry_image
before_script:
  - docker info

job create:
  stage: create_image
  script:
    - docker build -t centos/ansible .

job test:
  stage: test
  script:
    - docker run --name test centos/ansible ansible --vesion

job tagged:
  stage: tag_image
  script:
    - docker tag centos/ansible localhost:5000/ansible:v1

job registry:
  stage: registry_image
  script:
    - docker push localhost:5000/ansible:v1